import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google"; // NOTE: Only import if you use custom font configuration
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

// NOTE: The following font variables are currently unused. Uncomment if you want to use custom font configuration in the future.
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <body>
          <ThemeProvider 
            attribute="class" 
            defaultTheme="system" 
            enableSystem
            disableTransitionOnChange
            >
              {children}
            </ThemeProvider>
        </body>
      </html>
    </>
  );
}